version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: snackcornerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/snackcornerdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      HIBERNATE_SHOW_SQL: "false"
      HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  db_data:
