services:
  - type: web_service
    name: snackscorner
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
databases:
  - type: postgres
    name: snackscorner-db
    plan: starter
    postgresVersion: "15"
